config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root 'posts#index'

  # Sessions
  get "/login", to: "sessions#new"
  post "/login", to: "sessions#create"
  delete "/logout", to: "sessions#destroy"

  get "/posts_search", to: "posts#search", as: "posts_search"

  resources :posts do
    post "/images", to: "posts#create_image", as: "images"
    delete "/images/:id", to: "posts#destroy_image", as: "image"
  end

  resources :ebooks do
    post "/image", to: "ebooks#create_image", as: "image"
    delete "/image", to: "ebooks#destroy_image"
    post "/attachments", to: "ebooks#create_attachment", as: "attachments"
    delete "/attachment/:id", to: "ebooks#destroy_attachment", as: "attachment"
  end

  resources :pages, except: [:index] do
    post "/image", to: "pages#create_image", as: "images"
    delete "/image/:id", to: "pages#destroy_image", as: "image"
  end
end

app/views/shared/_error.html.haml
- if obj.present? && obj.errors.any?
  %div(class='alert alert-danger')
    %a.close(data-dismiss='alert') &#215;
    %h5 Please fix below errors:
    %ul
      - obj.errors.full_messages.each do |msg|
        %li= msg

app/views/shared/_float_object_spacer.html.haml
.div.pull-right(style="padding: 5px;")

app/views/shared/_footer.html.haml
%hr
.footer.row
  .col-md-6.col-lg-6
    %h6= prepend_icon_to_string Settings.site_owner.footer.left_column.title, Settings.site_owner.footer.left_column.icon
    = markdown Settings.site_owner.footer.left_column.content
  .col-md-6.col-lg-6
    %h6= prepend_icon_to_string Settings.site_owner.footer.right_column.title, Settings.site_owner.footer.right_column.icon
    = markdown Settings.site_owner.footer.right_column.content
%hr
.footer.row
  .col-lg-12
    %p.pull-right= Settings.site_owner.footer.bottom_line.html_safe

app/views/shared/_message.html.haml
- flash.each do |name, msg|
  %div(class="alert alert-#{name}" role="alert")
    %a.close(data-dismiss='alert') &#215;
    = content_tag :div, msg, :id => "flash_#{name}" if msg.is_a?(String)

app/views/shared/_navbar.html.haml
%nav
  .container-fluid
    .navbar-header
      = button_to "LW Studio", root_path, class: "navbar-toggle", data: {target: "#mainNav", toggle: "collapse"}, type: "button", method: :get
    = content_tag :div, fa_icon("navicon"), id: "menu-toggle", class: "btn btn-default fixed-toggle-navicon"
    = form_tag posts_search_path, class: "nav navbar-nav navbar-form form-inline navbar-right", method: :get do
      .input-group
        = text_field_tag :search_query, nil, class: "form-control", type: "text", placeholder: "Search Post for..."
        %span.input-group-btn
          = button_tag class: "btn btn-default" do
            = fa_icon "search"

app/views/shared/_page_header.html.haml
.page-header
  %h1
    = header

app/views/shared/_sidebar.html.haml
/ Sidebar
#sidebar-wrapper
  %ul.sidebar-nav
    %li.sidebar-brand
      = link_to "LW Studio", root_path, class: "sidebar-brand"
    %li.nav-bar-item
      = link_to "Blog", posts_path
    %li.nav-bar-item
      = link_to "eBooks", ebooks_path
    - menu_pages.each do |page|
      %li.nav-bar-item
        = link_to page_path(page) do
          - if page.is_draft
            = fa_icon("lock")
            = spaced_divider
          = page.title
    %li
      = mail_to Settings.site_owner.email, class: "nav-bar-icon" do
        = fa_icon "envelope"
      = link_to Settings.site_owner.github_profile, class: "nav-bar-icon" do
        = fa_icon "github"
      = link_to Settings.site_owner.linkedin_profile, class: "nav-bar-icon" do
        = fa_icon "linkedin"
    - if current_user.present?
      %li
        = link_to new_page_path do
          = fa_icon "plus"
          = spaced_divider
          = "New Page"
      %li
        = link_to logout_path, method: :delete do
          = fa_icon "sign-out"
          = spaced_divider
          = "Logout"