config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root 'posts#index'

  # Sessions
  get "/login", to: "sessions#new"
  post "/login", to: "sessions#create"
  delete "/logout", to: "sessions#destroy"

  get "/posts_search", to: "posts#search", as: "posts_search"

  resources :posts do
    post "/images", to: "posts#create_image", as: "images"
    delete "/images/:id", to: "posts#destroy_image", as: "image"
  end

  resources :ebooks do
    post "/image", to: "ebooks#create_image", as: "image"
    delete "/image", to: "ebooks#destroy_image"
    post "/attachments", to: "ebooks#create_attachment", as: "attachments"
    delete "/attachment/:id", to: "ebooks#destroy_attachment", as: "attachment"
  end

  resources :pages, except: [:index] do
    post "/image", to: "pages#create_image", as: "images"
    delete "/image/:id", to: "pages#destroy_image", as: "image"
  end
end

app/views/pages/_delete_page_button.html.haml
- if current_user && current_user == @page.user
  = link_to page_path(@page), class: "pull-right btn btn-default", method: :delete, data: { confirm: "Are you sure to delete this page?" } do
    = fa_icon "trash"

app/views/pages/_edit_page_button.html.haml
- if current_user && current_user == @page.user
  = link_to edit_page_path(@page), class: "pull-right btn btn-default" do
    = fa_icon "edit"

app/views/pages/_page.html.haml
- header = page.is_draft ? prepend_icon_to_string(page.title, "lock") : page.title
= render 'shared/page_header', header: header
.row.content
  .col-sm-12
    = markdown show_content(page.body, is_index: is_index)

app/views/pages/_page_form.html.haml
= render 'shared/error', obj: page
= render 'shared/error', obj: @image
= form_for page do |f|
  .form-group
    = f.label :title, id: "title"
    = f.text_field :title, id: "title", class: "form-control"
  .form-group
    = f.label :slug, id: "slug"
    = f.text_field :slug, id: "slug", class: "form-control"
  .row
    .form-group.col-sm-6.col-md-6.col-lg-6
      = f.label :published_at, "Scheduled to Publish At", id: "published_at"
      = f.date_field :published_at, value: ui_date(page.published_at), placeholder: "YYYY-MM-DD", id: "published-date", class: "form-control"
    .form-group.col-sm-6.col-md-6.col-lg-6
      = f.label :position, id: "position"
      = f.text_field :position, id: "position", class: "form-control"
  .checkbox
    %label
      = f.check_box :is_draft, value: 0
      = prepend_icon_to_string "Reserve to Draft Box.", "lock"
  .form-group
    = f.label :body, "Content", id: "body"
    = f.text_area :body, id: "body", class: "form-control", cols: 20, rows: 30
  = f.submit "#{page.new_record? ? "Create" : "Update"}", class: "btn btn-primary"
- unless page.new_record?
  %hr
  %h4.title Attached Image
  .row
    - page.images.each do |image|
      .col-sm-6.col-md-4.col-lg-3
        .panel.panel-default
          .panel-body
            = link_to page_image_path(page, image), class: "pull-right btn btn-default", method: :delete, data: { confirm: "Are you sure to delete this image?" } do
              = fa_icon "trash"
            = link_to image.asset.url(:medium) do
              = image_tag image.asset.url(:thumb), class: "img-responsive img-rounded"
  .row
    .col-sm-12
      = form_for @image, url: page_images_path(page), html: { multipart: true }, method: :page do |f|
        .form-group
          = f.file_field :asset
        = f.submit "Add new Image", class: "btn btn-default"

app/views/pages/edit.html.haml
- provide :title, "Edit #{@page.title}"
= render 'shared/page_header', header: "編輯：#{@page.title}"
= render 'page_form', page: @page

app/views/pages/new.html.haml
- provide :title, "Add new Page"
= render 'shared/page_header', header: "新增頁面"
= render 'page_form', page: @page

app/views/pages/show.html.haml
- provide :title, @page.title
= render 'delete_page_button'
= render "shared/float_object_spacer"
= render 'edit_page_button'
= render @page, is_index: false