config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root 'posts#index'

  # Sessions
  get "/login", to: "sessions#new"
  post "/login", to: "sessions#create"
  delete "/logout", to: "sessions#destroy"

  get "/posts_search", to: "posts#search", as: "posts_search"

  resources :posts do
    post "/images", to: "posts#create_image", as: "images"
    delete "/images/:id", to: "posts#destroy_image", as: "image"
  end

  resources :ebooks do
    post "/image", to: "ebooks#create_image", as: "image"
    delete "/image", to: "ebooks#destroy_image"
    post "/attachments", to: "ebooks#create_attachment", as: "attachments"
    delete "/attachment/:id", to: "ebooks#destroy_attachment", as: "attachment"
  end

  resources :pages, except: [:index] do
    post "/image", to: "pages#create_image", as: "images"
    delete "/image/:id", to: "pages#destroy_image", as: "image"
  end
end

app/models/post.rb
class Post < Entry
  include PgSearch
  multisearchable against: [:title, :payload]
  pg_search_scope :full_text_search, against: [:title, :payload]

  paginates_per Settings.content.show_number_on_index
  content_attr :body, :text
  has_many :images, class_name: 'Image', foreign_key: 'entry_id', dependent: :destroy

  validates :body, presence: true

  def self.search(query)
    pg_search_result_ids = self.full_text_search(query).ids
    sql_like_result_ids =
      query&.split&.inject(self.all.ids) do |result, query|
        result & self.where("payload ->> 'body' LIKE ?", "%#{query}%").ids
      end
    sql_like_result_ids ||= []
    result_ids = pg_search_result_ids + sql_like_result_ids
    self.where("id IN (?)", result_ids)
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :require_user, except: [:index, :show, :search]
  before_action :prepare_post, except: [:index, :new, :create, :search]
  before_action :require_post_owner, except: [:index, :new, :create, :show, :search]

  def search
    @posts =
      if current_user
        Post.search(params[:search_query]).page params[:page]
      else
        Post.published.search(params[:search_query]).page params[:page]
      end
    @highlights = params[:search_query]&.strip&.split
  end

  def index
    @posts =
      if current_user
        Post.all.order('created_at DESC').page params[:page]
      else
        Post.published.page params[:page]
      end
  end

  def new
    @post = Post.new
  end

  def show
    if !current_user && @post.is_draft
      flash[:danger] = "Access Denied"
      redirect_to :back
    end
  end

  def create
    @post = Post.new(post_params)
    @post.user = current_user

    if @post.save
      flash[:success] = "Created a new post!"
      redirect_to post_path(@post)
    else
      render :new
    end
  end

  def edit
    @image = Image.new
  end

  def update
    @post.assign_attributes(post_params)

    if @post.save
      flash[:success] = "Updated the post!"
      redirect_to post_path(@post)
    else
      render :edit
    end
  end

  def destroy
    if @post.destroy
      flash[:success] = "Deleted the post!"
      redirect_to posts_path
    else
      render :show
    end
  end

  def create_image
    if params[:image].present?
      @image = Image.new(image_params)
      @image.entry = @post
      flash[:success] = "Created new Image!" if @image.save
    else
      flash[:danger] = "Please provide Image to upload."
    end
    redirect_to edit_post_path(@post)
  end

  def destroy_images
    @image = Image.find_by_id params[:id]
    if @image.present? && @image.destroy
      flash[:success] = "Deleted the Image!"
    end
    redirect_to edit_post_path(@post)
  end

  private

  def post_params
    params.require(:post).permit(:body, :author_name, :published_at, :is_draft, :title, :slug)
  end

  def prepare_post
    @post = Post.find_by_slug(params[:post_id] || params[:id])
  end

  def require_post_owner
    require_owner(@post)
  end

  def image_params
    params.require(:image).permit(:asset)
  end
end

app/views/posts/_add_new_post_button.html.haml
- if current_user
  = link_to new_post_path, class: "pull-right btn btn-primary" do
    = "New Post"

app/views/posts/_delete_post_button.html.haml
- if current_user && current_user == @post.user
  = link_to post_path(@post), class: "pull-right btn btn-default", method: :delete, data: { confirm: "Are you sure to delete this post?" } do
    = fa_icon "trash"

app/views/posts/_disqus_comment_count.html.haml
%script#dsq-count-scr{:async => "", :src => "#{Settings.disqus.count_src}"}

app/views/posts/_disqus_comment_field.html.haml
#disqus_thread
:javascript
  /**
   *  RECOMMENDED CONFIGURATION VARIABLES: EDIT AND UNCOMMENT THE SECTION BELOW TO INSERT DYNAMIC VALUES FROM YOUR PLATFORM OR CMS.
   *  LEARN WHY DEFINING THESE VARIABLES IS IMPORTANT: https://disqus.com/admin/universalcode/#configuration-variables */
  /**/
  var disqus_config = function () {
      this.page.url = "#{post_url(post)}";  // Replace PAGE_URL with your page's canonical URL variable
      this.page.identifier = "#{post.slug}"; // Replace PAGE_IDENTIFIER with your page's unique identifier variable
  };

  (function() { // DON'T EDIT BELOW THIS LINE
      var d = document, s = d.createElement('script');
      s.src = "#{Settings.disqus.comment_src}";
      s.setAttribute('data-timestamp', +new Date());
      (d.head || d.body).appendChild(s);
  })();
%noscript
  Please enable JavaScript to view the
  %a{:href => "https://disqus.com/?ref_noscript"} comments powered by Disqus.

app/views/posts/_edit_post_button.html.haml
- if current_user && current_user == @post.user
  = link_to edit_post_path(@post), class: "pull-right btn btn-default" do
    = fa_icon "edit"

app/views/posts/_post.html.haml
- is_index ||= false
- hide_comment ||= false
%h4.title
  = link_to post_path(post), class: "post-title" do
    = post.is_draft ? fa_icon("lock") : fa_icon("newspaper-o")
    = spaced_divider
    = highlight_if_needed(post.title, @highlights)
.row.meta.text-muted
  .col-sm-12.col-md-6
    %p
      %span
        = fa_icon "user"
        = spaced_divider
        = post.author_name
      = spaced_divider
      %span
        = fa_icon "clock-o"
        = spaced_divider
        = l post.published_at, format: :post
      = spaced_divider
      %span
        = fa_icon "edit"
        = spaced_divider
        = l post.updated_at, format: :post
      = spaced_divider
      %span
        = fa_icon "comment"
        = spaced_divider
        = link_to "0 comments", "#{post_path(post)}#disqus_thread", data: { "disqus-identifier" => "#{post.slug}" }
.row.content
  .col-sm-12
    = highlight_if_needed(markdown(show_content(post.body, is_index: is_index)), @highlights)
    - if is_index && post.body.include?(Settings.content.readmore_tag)
      = link_to "READ MORE >>", post_path(post), class: "pull-right"
    - if !is_index && !hide_comment
      %hr
      = render "disqus_comment_field", post: post

app/views/posts/_post_form.html.haml
= render 'shared/error', obj: post
= render 'shared/error', obj: @image
= form_for post do |f|
  .form-group
    = f.label :title, id: "title"
    = f.text_field :title, id: "title", class: "form-control"
  .form-group
    = f.label :slug, id: "slug"
    = f.text_field :slug, id: "slug", class: "form-control"
  .row
    .form-group.col-sm-6.col-md-6.col-lg-6
      = f.label :published_at, "Scheduled to Publish At", id: "published_at"
      = f.date_field :published_at, value: ui_date(post.published_at), placeholder: "YYYY-MM-DD", id: "published-date", class: "form-control"
    .checkbox.col-sm-6.col-md-6.col-lg-6
      %label
        = f.check_box :is_draft, value: 0
        = prepend_icon_to_string "Reserve to Draft Box.", "lock"
  .form-group
    = f.label :body, "Content, use '#{Settings.content.readmore_tag}' to separate the brief intro in Index view.", id: "body"
    = f.text_area :body, id: "body", class: "form-control", cols: 20, rows: 30
  = f.submit "#{post.new_record? ? "Create" : "Update"}", class: "btn btn-primary"
- unless post.new_record?
  %hr
  %h4.title Attached Image
  .row
    - post.images.each do |image|
      .col-sm-6.col-md-4.col-lg-3
        .panel.panel-default
          .panel-body
            = link_to post_image_path(post, image), class: "pull-right btn btn-default", method: :delete, data: { confirm: "Are you sure to delete this image?" } do
              = fa_icon "trash"
            = link_to image.asset.url(:medium) do
              = image_tag image.asset.url(:thumb), class: "img-responsive img-rounded"
  .row
    .col-sm-12
      = form_for @image, url: post_images_path(post), html: { multipart: true }, method: :post do |f|
        .form-group
          = f.file_field :asset
        = f.submit "Add new Image", class: "btn btn-default"

app/views/posts/edit.html.haml
- provide :title, @post.title
= render 'shared/page_header', header: "編輯：#{@post.title}"
= render 'post_form', post: @post

app/views/posts/index.html.haml
- provide :title, "Blog"
= render "add_new_post_button"
= render @posts, is_index: true, hide_comment: true
.row
  .col-sm-12= paginate @posts, theme: 'twitter-bootstrap-3', pagination_class: "pagination-sm"
  = render "disqus_comment_count"

app/views/posts/new.html.haml
- provide :title, @post.title
= render 'shared/page_header', header: "新增文章"
= render 'post_form', post: @post

app/views/posts/search.html.haml
- provide :title, "Search Blog Post"
= render "shared/page_header", header: "Search Result"
.row
  .col-sm-12
    %p= "You searched for: #{@highlights&.join(" ")}"
    %p= "Found #{pluralize(@posts.count, 'post')}."
- if @posts.present?
  %hr
= render @posts, is_index: false, hide_comment: true
.row
  .col-sm-12= paginate @posts, theme: 'twitter-bootstrap-3', pagination_class: "pagination-sm"

app/views/posts/show.html.haml
- provide :title, @post.title
= render "add_new_post_button"
= render "shared/float_object_spacer"
= render 'delete_post_button'
= render "shared/float_object_spacer"
= render 'edit_post_button'
= render @post, is_index: false