config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root 'posts#index'

  # Sessions
  get "/login", to: "sessions#new"
  post "/login", to: "sessions#create"
  delete "/logout", to: "sessions#destroy"

  get "/posts_search", to: "posts#search", as: "posts_search"

  resources :posts do
    post "/images", to: "posts#create_image", as: "images"
    delete "/images/:id", to: "posts#destroy_image", as: "image"
  end

  resources :ebooks do
    post "/image", to: "ebooks#create_image", as: "image"
    delete "/image", to: "ebooks#destroy_image"
    post "/attachments", to: "ebooks#create_attachment", as: "attachments"
    delete "/attachment/:id", to: "ebooks#destroy_attachment", as: "attachment"
  end

  resources :pages, except: [:index] do
    post "/image", to: "pages#create_image", as: "images"
    delete "/image/:id", to: "pages#destroy_image", as: "image"
  end
end

app/models/ebook.rb
class Ebook < Entry
  paginates_per Settings.content.show_number_on_index
  has_many :attachments, class_name: 'Attachment', foreign_key: 'entry_id', dependent: :destroy
  has_one :image, class_name: 'Image', foreign_key: 'entry_id', dependent: :destroy
  content_attr :introduction, :text
  content_attr :references, :text
  content_attr :pdf_url, :string
  content_attr :epub_url, :string
  content_attr :mobi_url, :string
  content_attr :cover_url, :string

  validates :introduction, presence: true

  def reference_infos
    # description|url,description|url
    references&.strip&.split(",")&.map do |resource|
      {
        url: resource&.split("|")&.last,
        description: resource&.split("|")&.first
      }
    end
  end
end

app/controllers/ebooks_controller.rb
class EbooksController < ApplicationController
  before_action :require_user, except: [:index]
  before_action :prepare_ebook, except: [:index, :new, :create]
  before_action :require_ebook_owner, except: [:index, :new, :create, :show]

  def index
    @ebooks =
      if current_user
        Ebook.all.order('created_at DESC').page params[:page]
      else
        Ebook.published.page params[:page]
      end
  end

  def new
    @ebook = Ebook.new
  end

  def create
    @ebook = Ebook.new
    @ebook.assign_attributes(ebook_params)
    @ebook.user = current_user

    if @ebook.save
      flash[:success] = "Updated the ebook!"
      redirect_to ebooks_path(@ebook)
    else
      render :edit
    end
  end

  def edit
    @attachment = Attachment.new
    @image = Image.new
  end

  def update
    @ebook.assign_attributes(ebook_params)

    if @ebook.save
      flash[:success] = "Updated the ebook!"
      redirect_to ebooks_path(@ebook)
    else
      render :edit
    end
  end

  def destroy
    if @ebook.destroy
      flash[:success] = "Deleted the ebook!"
    end
    redirect_to ebooks_path
  end

  def create_image
    if params[:image].present?
      @image = Image.new(image_params)
      @image.entry = @ebook
      if @image.save
        # make sure there is
        Image.where(entry: @ebook)[0..-2]&.map(&:destroy)
        flash[:success] = "Update Cover Image!"
      end
    else
      flash[:danger] = "Please provide Image to upload."
    end
    redirect_to :back
  end

  def destroy_image
    @images = Image.where(entry: @ebook)
    if @images.destroy_all
      flash[:success] = "Deleted the image!"
    end
    redirect_to :back
  end

  def create_attachment
    if params[:attachment].present?
      @attachment = Attachment.new(attachment_params)
      @attachment.entry = @ebook
      if @attachment.save
        flash[:success] = "Added new attachment."
      else
        flash[:danger] = "Opps, something wrong with your upload."
      end
    else
      flash[:danger] = "Please provide attachment to upload."
    end
    redirect_to :back
  end

  def destroy_attachment
    @attachment = Attachment.find_by_id params[:id]
    if @attachment.present? && @attachment.destroy
      flash[:success] = "Deleted the attachment!"
    end
    redirect_to :back
  end

  private

  def prepare_ebook
    @ebook = Ebook.find_by_slug(params[:ebook_id] || params[:id])
  end

  def require_ebook_owner
    require_owner(@ebook)
  end

  def attachment_params
    params.require(:attachment).permit(:asset)
  end

  def image_params
    params.require(:image).permit(:asset)
  end

  def ebook_params
    params.require(:ebook).permit(:cover_url, :epub_url, :pdf_url, :mobi_url, :introduction, :references, :author_name, :is_draft, :published_at, :title, :slug)
  end
end

app/views/ebooks/_attachment_list.html.haml
- if ebook.attachments.present?
  %ul.list-group
    - ebook.attachments.each do |attachment|
      %li.list-group-item
        - if current_user && current_user == ebook.user
          = link_to ebook_attachment_path(ebook, attachment), class: "badge", method: :delete, data: { confirm: "Are you sure to delete this attachment?" } do
            = fa_icon "trash"
        = prepend_icon_to_link_to attachment.asset_file_name, attachment.asset.url, "file-o"

app/views/ebooks/_delete_ebook_button.html.haml
- if current_user && current_user == ebook.user
  = link_to ebook_path(ebook), class: "pull-right btn btn-default", method: :delete, data: { confirm: "Are you sure to delete this ebook?" } do
    = fa_icon "trash"

app/views/ebooks/_ebook.html.haml
.row
  .col-sm-12.col-md-10.col-lg-10
    %h4.title= prepend_icon_to_string ebook.title, (ebook.is_draft ? "lock" : "book")
  .col-sm-12.col-md-2.col-lg-2
    = render "delete_ebook_button", ebook: ebook
    = render "shared/float_object_spacer"
    = render 'edit_ebook_button', ebook: ebook
.row
  .col-sm-12
    - cover_url = ebook.image.present? ? ebook.image.asset.url(:small) : ebook.cover_url
    = image_tag cover_url, class: "pull-left img-responsive img-rounded", style: "margin-right: 1em; margin-bottom: 1em; width: 150px;" if cover_url.present?
    %p.meta.text-muted= prepend_icon_to_string ebook.author_name, "user-secret"
    - if ebook.references.present?
      - ebook.reference_infos.each do |info|
        %p.meta.text-muted
          = prepend_icon_to_link_to (info[:description] || info[:url]), info[:url], "external-link"
    = render "ebooks_download_button_group", ebook: ebook unless ebook.attachments.present?
    %p.content= markdown ebook.introduction
- unless ebook.pdf_url.present? || ebook.epub_url.present? || ebook.mobi_url.present?
  .row
    .col-sm-12
      = render 'attachment_list', ebook: ebook

app/views/ebooks/_ebook_form.html.haml
= render 'shared/error', obj: ebook.image unless ebook.new_record?
= render 'shared/error', obj: ebook
= render 'shared/error', obj: @attachment unless ebook.new_record?
- header = ebook.new_record? ? "新增 電子書" : "編輯：#{ebook.title}"
= render 'shared/page_header', header: header
= form_for ebook do |f|
  .form-group
    = f.label :title, id: "title"
    = f.text_field :title, id: "title", class: "form-control"
  .form-group
    = f.label :slug, id: "slug"
    = f.text_field :slug, id: "slug", class: "form-control #{"disabled" unless ebook.new_record?}"
  .form-group
    = f.label :cover_url, id: "cover_url"
    = f.text_field :cover_url, id: "cover_url", class: "form-control"
  .form-group
    = f.label :pdf_url, id: "pdf_url"
    = f.text_field :pdf_url, id: "pdf_url", class: "form-control"
  .form-group
    = f.label :epub_url, id: "epub_url"
    = f.text_field :epub_url, id: "epub_url", class: "form-control"
  .form-group
    = f.label :mobi_url, id: "mobi_url"
    = f.text_field :mobi_url, id: "mobi_url", class: "form-control"
  .row
    .form-group.col-sm-6.col-md-6.col-lg-6
      = f.label :author_name, id: "author_name"
      = f.text_field :author_name, id: "author_name", class: "form-control"
    .form-group.col-sm-6.col-md-6.col-lg-6
      = f.label :published_at, "Scheduled to Publish At", id: "published_at"
      = f.date_field :published_at, value: ui_date(ebook.published_at), placeholder: "YYYY-MM-DD", id: "published-date", class: "form-control"
  .checkbox
    %label
      = f.check_box :is_draft, value: 0
      = prepend_icon_to_string "Reserve to Draft Box.", "lock"
  .form-group
    = f.label :references, "Resources: description|url,description|url", id: "introduction"
    = f.text_area :references, id: "references", class: "form-control", cols: 20, rows: 5
  .form-group
    = f.label :introduction, "Introduction, use '#{Settings.content.readmore_tag}' to separate the brief intro in Index view.", id: "introduction"
    = f.text_area :introduction, id: "introduction", class: "form-control", cols: 20, rows: 10
  = f.submit "#{ebook.new_record? ? "Create" : "Update"}", class: "btn btn-primary"
- unless ebook.new_record?
  %hr
  .row
    .col-sm-12.col-md-6.col-lg-6
      %h4.title Cover Image
      .panel.panel-default
        .panel-body
          = link_to ebook_image_path(ebook), class: "pull-right btn btn-default", method: :delete, data: { confirm: "Are you sure to delete this image?" } do
            = fa_icon "trash"
          = image_tag ebook.image.asset.url(:small), class: "img-responsive img-rounded" if ebook.image.present?
      = form_for @image, url: ebook_image_path(ebook), html: { multipart: true } do |f|
        .form-group
          = f.file_field :asset
        = f.submit "Add new Image", class: "btn btn-default"
    .col-sm-12.col-md-6.col-lg-6
      %h4.title Attachments
      = render 'attachment_list', ebook: ebook
      = form_for @attachment, url: ebook_attachments_path(ebook), html: { multipart: true } do |f|
        .form-group
          = f.file_field :asset
        = f.submit "Add new Attachment", class: "btn btn-default"

app/views/ebooks/_ebooks_download_button_group.html.haml
- if ebook.pdf_url.present? || ebook.epub_url.present? || ebook.mobi_url.present?
  .btn-group
    - if ebook.pdf_url.present?
      = button_tag ebook.pdf_url, class: "btn btn-default" do
        = prepend_icon_to_string "PDF", "file-o"
    - if ebook.mobi_url.present?
      = button_tag ebook.mobi_url, class: "btn btn-default" do
        = prepend_icon_to_string "mobi", "file-o"
    - if ebook.epub_url.present?
      = button_tag ebook.epub_url, class: "btn btn-default" do
        = prepend_icon_to_string "ePub", "file-o"
%hr

app/views/ebooks/_edit_ebook_button.html.haml
- if current_user && current_user == ebook.user
  = link_to edit_ebook_path(ebook), class: "pull-right btn btn-default" do
    = fa_icon "edit"

app/views/ebooks/edit.html.haml
- provide :title, "Edit #{@ebook.title}"
= render 'ebook_form', ebook: @ebook

app/views/ebooks/index.html.haml
- provide :title, "自由電子書"
= render "shared/page_header", header: "自由電子書"
.content= markdown Settings.site_owner.ebook_intro
- if current_user
  = link_to new_ebook_path, class: "btn btn-primary" do
    = fa_icon "plus"
    = "New eBook"
%hr
= render @ebooks, is_index: true

app/views/ebooks/new.html.haml
- provide :title, "Add new Ebook"
= render 'ebook_form', ebook: @ebook